package main

import (
	"flag"
	"log"

	rd "github.com/0xspiderr/gododocs/internal/renderer"
	st "github.com/0xspiderr/gododocs/internal/settings"
	wr "github.com/0xspiderr/gododocs/internal/writer"
	xmlp "github.com/0xspiderr/gododocs/internal/xmlparser"
)

func parseFlags() *st.Settings {
	in := flag.String("in", st.DefaultInDir, "the input directory which contains all .xml files"+
		"generated by the godocs tool")
	out := flag.String("out", st.DefaultOutDir, "the output directory where the converted .xml files"+
		"will be placed")
	flag.Parse()
	return &st.Settings{InDir: *in, OutDir: *out}
}

func main() {
	settings := parseFlags()
	classes, err := xmlp.Parse(settings.InDir)
	if err != nil {
		log.Fatal(err)
	}

	for _, c := range classes {
		md, err := rd.Render(c)
		if err != nil {
			log.Fatal(err)
		}
		if err := wr.Write(settings.OutDir, c.Name, md); err != nil {
			log.Fatal(err)
		}
	}
}
