package main

import (
	"flag"
	"fmt"
	"log"
	"os"

	rd "github.com/0xspiderr/gododocs/internal/renderer"
	st "github.com/0xspiderr/gododocs/internal/settings"
	wr "github.com/0xspiderr/gododocs/internal/writer"
	xmlp "github.com/0xspiderr/gododocs/internal/xmlparser"
)

func parseFlags() *st.Settings {
	in := flag.String("in", st.DefaultInDir, "the input directory which contains all .xml files"+
		"generated by the godocs tool")
	out := flag.String("out", st.DefaultOutDir, "the output directory where the converted .xml files"+
		"will be placed")
	flag.Parse()
	return &st.Settings{InDir: *in, OutDir: *out}
}

func main() {
	settings := parseFlags()
	classes, err := xmlp.Parse(settings.InDir)
	if err != nil {
		log.Fatal(err)
	}

	// append errors instead of Fatal log so the parser
	// continues on the next classes
	var errs []error
	rendered := make(map[string]string, len(classes))
	for _, c := range classes {
		md, err := rd.Render(c)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", c.Name, err))
			continue
		}
		rendered[c.Name] = md
	}

	for name, md := range rendered {
		if err := wr.Write(settings.OutDir, name, md); err != nil {
			errs = append(errs, err)
		}
	}

	if len(errs) > 0 {
		for _, e := range errs {
			fmt.Fprintln(os.Stderr, e)
		}
		os.Exit(1)
	}
}
